import jsPDF from "jspdf";
import { dedupeCitations } from "@/lib/citations";

const MARGIN_PT = 48;
const FOOTER_RESERVE_PT = 52;
const LINE_H = 13;
const MAX_IMG_HEIGHT_PT = 420;

function stripMarkdownLight(s) {
  if (s == null) return "";
  return String(s)
    .replace(/```[\s\S]*?```/g, "[code block omitted]")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/^\s*>\s?/gm, "")
    .replace(/\|/g, " ")
    .replace(/^\s*[-*]\s+/gm, "• ")
    .trim();
}

function sanitizeFilename(name) {
  const t = String(name || "report").replace(/[<>:"/\\|?*]+/g, "_").slice(0, 80);
  return t || "report";
}

function drawFooters(doc) {
  const n = doc.internal.getNumberOfPages();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= n; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(110, 110, 120);
    doc.text("Generated by CFOai.", MARGIN_PT, h - 28);
    doc.text(`Page ${i} of ${n}`, w - MARGIN_PT, h - 28, { align: "right" });
  }
}

function drawContinuationHeader(doc, documentName) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(16, 17, 20);
  doc.rect(0, 0, w, 40, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(0, 200, 230);
  doc.text("CFOai", MARGIN_PT, 26);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(160, 160, 170);
  const short = documentName.length > 70 ? `${documentName.slice(0, 67)}…` : documentName;
  doc.text(short, MARGIN_PT + 52, 26);
}

/**
 * Build a multi-page CFOai dashboard PDF (summary, optional chart image, chat transcript).
 * Call from the browser only (uses jsPDF).
 */
export function exportCfoaiDashboardPdf({
  summary = "",
  documentName = "",
  generatedAt = new Date(),
  chartImageDataUrl = null,
  chatMessages = []
}) {
  const doc = new jsPDF({ unit: "pt", format: "letter", orientation: "portrait" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const innerW = pageW - 2 * MARGIN_PT;
  const dateStr =
    generatedAt instanceof Date
      ? generatedAt.toLocaleString(undefined, {
          dateStyle: "medium",
          timeStyle: "short"
        })
      : String(generatedAt);

  let y = MARGIN_PT;

  const newPage = () => {
    doc.addPage();
    drawContinuationHeader(doc, documentName);
    y = 56;
  };

  const ensureSpace = (neededPt) => {
    if (y + neededPt > pageH - FOOTER_RESERVE_PT) {
      newPage();
    }
  };

  // —— Cover header ——
  doc.setFillColor(10, 10, 12);
  doc.rect(0, 0, pageW, 100, "F");
  doc.setDrawColor(0, 212, 255);
  doc.setLineWidth(2);
  doc.line(MARGIN_PT, 96, pageW - MARGIN_PT, 96);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(0, 212, 255);
  doc.text("CFOai", MARGIN_PT, 52);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(200, 200, 210);
  doc.text("Financial intelligence export", MARGIN_PT, 74);

  y = 118;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(40, 40, 48);
  doc.text("Document", MARGIN_PT, y);
  y += LINE_H + 2;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(55, 55, 65);
  const docLines = doc.splitTextToSize(documentName || "—", innerW);
  doc.text(docLines, MARGIN_PT, y);
  y += docLines.length * LINE_H + 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(40, 40, 48);
  doc.text("Generated", MARGIN_PT, y);
  y += LINE_H + 2;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(55, 55, 65);
  doc.text(dateStr, MARGIN_PT, y);
  y += LINE_H + 28;

  // —— Financial Summary ——
  ensureSpace(60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(25, 28, 35);
  doc.text("Financial Summary", MARGIN_PT, y);
  y += LINE_H + 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(45, 48, 58);
  const summaryBody = summary.trim() ? stripMarkdownLight(summary) : "(No summary text yet.)";
  const summaryLines = doc.splitTextToSize(summaryBody, innerW);
  for (const line of summaryLines) {
    ensureSpace(LINE_H);
    doc.text(line, MARGIN_PT, y);
    y += LINE_H;
  }
  y += 20;

  // —— Charts (image) ——
  if (chartImageDataUrl) {
    ensureSpace(80);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(25, 28, 35);
    doc.text("Metric charts", MARGIN_PT, y);
    y += LINE_H + 12;

    try {
      const props = doc.getImageProperties(chartImageDataUrl);
      const imgW = innerW;
      const imgH = Math.min((props.height * imgW) / props.width, MAX_IMG_HEIGHT_PT);
      ensureSpace(imgH + 16);
      doc.addImage(chartImageDataUrl, "PNG", MARGIN_PT, y, imgW, imgH, undefined, "FAST");
      y += imgH + 24;
    } catch {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(120, 120, 130);
      doc.text("(Chart image could not be embedded.)", MARGIN_PT, y);
      y += LINE_H + 12;
    }
  }

  // —— Chat ——
  ensureSpace(60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(25, 28, 35);
  doc.text("Chat conversation", MARGIN_PT, y);
  y += LINE_H + 12;

  if (!chatMessages.length) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 110);
    doc.text("(No chat messages yet.)", MARGIN_PT, y);
    y += LINE_H + 16;
  } else {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    for (const msg of chatMessages) {
      const role = msg.role === "user" ? "Question" : "Answer";
      const raw = typeof msg.content === "string" ? msg.content : "";
      const body = stripMarkdownLight(raw);
      const prefix = `${role}: `;
      const wrapped = doc.splitTextToSize(prefix + body, innerW);
      const blockH = wrapped.length * LINE_H + (msg.role === "assistant" && msg.citations?.length ? LINE_H * 2 : 8);
      ensureSpace(blockH);
      doc.setFont("helvetica", msg.role === "user" ? "bold" : "normal");
      if (msg.role === "user") {
        doc.setTextColor(0, 95, 115);
      } else {
        doc.setTextColor(45, 48, 58);
      }
      doc.text(wrapped, MARGIN_PT, y);
      y += wrapped.length * LINE_H;

      if (msg.role === "assistant" && Array.isArray(msg.citations) && msg.citations.length) {
        const cites = dedupeCitations(msg.citations)
          .map((c) => `${c.file}${c.page != null ? ` p.${c.page}` : ""}`)
          .join("; ");
        const citeLines = doc.splitTextToSize(`Sources: ${cites}`, innerW);
        doc.setFont("helvetica", "italic");
        doc.setFontSize(8);
        doc.setTextColor(90, 95, 105);
        for (const cl of citeLines) {
          ensureSpace(LINE_H);
          doc.text(cl, MARGIN_PT, y);
          y += LINE_H - 2;
        }
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
      }
      y += 10;
    }
  }

  drawFooters(doc);

  const safe = sanitizeFilename(documentName);
  const day = generatedAt instanceof Date ? generatedAt.toISOString().slice(0, 10) : "export";
  doc.save(`CFOai-${safe}-${day}.pdf`);
}
